services:
  postgres:
    container_name: backend-db
    image: postgres:17.4
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - ./init/:/docker-entrypoint-initdb.d
      - backend-db:/var/lib/postgresql/data
volumes:
  backend-db: